insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values(101,'Reliance',2568.75);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values(102,'ITC',260.42);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values(103,'AdaniPort',784.04);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) values(104,'Infosis',1648.64);